# Programming Assignment 2

## Problem 1: Normalization Problem

In [65]:
import numpy as np

In [66]:
x = np.random.random((5,5))

In [67]:
xnormalization = (x - x.mean())/x.std()

In [68]:
np.save("X_normalized.npy", xnormalization)

In [69]:
x

array([[0.94375257, 0.45416557, 0.45599101, 0.71587365, 0.63083988],
       [0.62288047, 0.696087  , 0.52827141, 0.0893541 , 0.08866695],
       [0.04533112, 0.98611285, 0.34029355, 0.95448401, 0.20177033],
       [0.40276833, 0.2286073 , 0.73666572, 0.03744824, 0.98719605],
       [0.15628011, 0.78244284, 0.69315889, 0.8632455 , 0.80174457]])

In [70]:
n = np.load("X_normalized.npy")
n

array([[ 1.30124133, -0.26783957, -0.26198923,  0.57091054,  0.2983852 ],
       [ 0.27287602,  0.50749617, -0.03033724, -1.43702648, -1.43922873],
       [-1.57811606,  1.43700209, -0.63278884,  1.3356346 , -1.0767429 ],
       [-0.43256295, -0.9907329 ,  0.63754718, -1.60337995,  1.44047366],
       [-1.22253484,  0.78425859,  0.49811182,  1.04322363,  0.84611885]])

## Problem 2: Divisible by 3 Problem

In [71]:
import numpy as np

In [72]:
a = np.arange(1, 101)

In [73]:
squarenumbers = a ** 2

In [74]:
squarenumbers.size

100

In [75]:
A = squarenumbers.reshape(10, 10)

In [76]:
A #checking final array if process was done right

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [77]:
numbersdivby3 = A[A % 3 == 0]

In [78]:
numbersdivby3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [79]:
np.save("div_by_3.npy", numbersdivby3)

In [82]:
loaded = np.load("div_by_3.npy") #checking if saved

In [83]:
loaded

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

# ---------------------------------------END---------------------------------------------